services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: KEYBOARCAT
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-$(openssl rand -base64 12)}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
