on:
    push:
        branches:
            - main
        paths:
            - "Dockerfile"
            - "src/**"
            - "Cargo.toml"
            - ".github/workflows/build.yaml"

jobs:
    build:
        name: Build and Push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: kaylendog
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      ghcr.io/kaylendog/keyboard-cat:latest
                      ghcr.io/kaylendog/keyboard-cat:${{ github.sha }}
